runtime: python310

entrypoint: gunicorn -c gunicorn.conf.py --threads 4 server.wsgi:application

env_variables:
  SECRET_KEY: "x&5lse$^otqe2n_tx3)(fwgz5o!1cn-32nkx^((5436#&j32lg"
  DEBUG: 0

instance_class: F2

handlers:
  - url: /static
    static_dir: staticfiles-cdn/

  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.5